### ISSUE TITLE
Determine overall priority of user stories

### ISSUE THREAD

**Issue by sharanyasisodia** [lgmueller/smarter-university-system#53]
Activity for #26

**Comment by sharanyasisodia** [comment]
Determine overall priority of user stories based on the priority assigned by all the group members.

**Comment by lgmueller** [comment]
reveiw priorities once all tress have been reviewed

**Comment by AmyPrakash** [comment]
Added the Team's aggregate priority column

**Comment by AmyPrakash** [comment]
The bi graph review has been completed and overall priority updated.
